name: Release Packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches: ["main", "alpha", "beta", "rc"]
    paths:
      - ".changeset/**"
      - "services/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality-checks:
    uses: apart-re/monorepo/.github/workflows/quality-checks.yml@main
    secrets: inherit

  release:
    name: Release Packages
    needs: [quality-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup environment
        uses: apart-re/monorepo/.github/actions/setup-environment@main
        with:
          os: ubuntu-latest
      - name: Release Docker Images
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: pnpm release:docker
        
