name: Release Packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: override release tag
        required: false
  push:
    branches: ["main", "alpha", "beta", "rc"]
    paths:
      - ".changeset/**"
      - "packages/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality-checks:
    uses: apart-re/monorepo/.github/workflows/quality-checks.yml@main
    secrets: inherit

  release-packages:
    name: Release Packages
    needs: [quality-checks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup environment
        uses: apart-re/monorepo/.github/actions/setup-environment@main
        with:
          os: ubuntu-latest
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release:packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
